MLWebApp/urls.py
from MLWebApp import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'MLWebApp'
urlpatterns = [
    path('', views.MLWebAppView.as_view(), name='MLWebApp'),
    path('<datasetid>/', views.delete, name='delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MLWebAppProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MLWebApp.urls')),
]

MLWebApp/models.py
from django.db import models

# Create your models here.
class FileModel(models.Model):
    file_name = models.CharField(max_length=50)
    file_content = models.FileField(upload_to="upload")

MLWebApp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import FormParser, MultiPartParser, JSONParser
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import status
from django.conf import settings
from .models import FileModel
from .serializers import FileSerializer
import os
from django.http import HttpResponse, Http404

# Create your views here.
def get_file_list():
    files = FileModel.objects.values_list('file_name', flat = True)
    return files.distinct()

def get_algorithm_list():
    return ['PimaDiabetesClassifier','WineQualityRegressor','NBAOutlier']

class MLWebAppView(APIView):
    parser_classes = [JSONParser, FormParser, MultiPartParser]
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'index.html'
    
    # See Django REST Request class here:
    # https://www.django-rest-framework.org/api-guide/requests/
    def get(self, request):
        return Response({'files': get_file_list(),
                         'algorithms': get_algorithm_list()},
                        status=status.HTTP_200_OK)
    def post(self, request):
        # Upload form  
        if 'upload' in request.data:
            file_serializer = FileSerializer(data=request.data)
            if file_serializer.is_valid():
                file_serializer.save()
                #f = FileModel.objects.all()
                #return Response({'f':f, 'status': 'Upload successful!', 'files': get_file_list(), 'algorithms': get_algorithm_list()}, status=status.HTTP_201_CREATED)
                return Response({'status': 'Upload successful!',
                                'files': get_file_list(), 'algorithms': get_algorithm_list()},
                                status=status.HTTP_201_CREATED)
            else:
                return Response(status=status.HTTP_400_BAD_REQUEST)
            
        elif 'delete' in request.data:
                try:
                    query_file_name = request.data['file_name']
                    query_algorithm = request.data['algorithm']
                    file_obj = FileModel.objects.get(file_name=query_file_name)
                    file_obj.file_content.delete()
                    file_obj.delete()
                    return Response({ 'status2': 'delete successful!', 'files': get_file_list(), 'algorithms': get_algorithm_list()}, status=status.HTTP_200_OK)

                except:
                    print('failed to delete a file')
                    return Response({'status2': 'delete failed!', 'files': get_file_list(), 'algorithms': get_algorithm_list()}, status=status.HTTP_200_OK)

            
        elif 'analytic' in request.data:
            # Run analytics on dataset as specified by file_name and
            # analytic_id received in the post request
            query_file_name = request.data['file_name']
            query_algorithm = request.data['algorithm']
            # Find file path to local folder
            file_obj = FileModel.objects.get(file_name=query_file_name)
            file_path = file_obj.file_content
            # Find algorithm
            algo_obj = get_algorithm(query_algorithm)
            analyticresult = run_analytic(file_path, algo_obj)
            return Response({'files':get_file_list(),
            'algorithms':get_algorithm_list(),
            'result_plot':analyticresult},
            status=status.HTTP_200_OK)

def get_algorithm(name):
    if name == 'PimaDiabetesClassifier':
        from .myhwone import run_algo1
        return run_algo1
    elif name == 'WineQualityRegressor':
        from .myhwtwo import run_algo2
        return run_algo2
    elif name == 'NBAOutlier':
        from .myhwthree import run_algo3
        return run_algo3
    else:
        # Http404 is imported from django.http
        raise Http404('<h1>Target algorithm not found</h1>')
    
def delete(request, datasetid):
    try:
        file_obj = FileModel.objects.get(file_name=datasetid)
        file_obj.file_content.delete()
        file_obj.delete()
        return redirect('MLWebApp:MLWebApp')
        #return Response({ 'status2': 'delete successful!', 'files': get_file_list(), 'algorithms': get_algorithm_list()}, status=status.HTTP_200_OK)
    except:
        print('failed to delete a file')
        return redirect('MLWebApp:MLWebApp')
        #return Response({'status2': 'delete failed!', 'files': get_file_list(), 'algorithms': get_algorithm_list()}, status=status.HTTP_200_OK)
    
def run_analytic(file_path, algo):
    file_abs_path = os.path.join(settings.MEDIA_ROOT, str(file_path))
    return algo(file_abs_path)

MLWebApp/templates/analytic_template.html
<!-- Run Analytic html -->
<form method="post" enctype="multipart/form-data" id='analytic'>
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <!-- select dataset to work on -->
            <div class="col">
            <h5>Select Dataset</h5>
            {% if files|length < 1 %}
                <p class="text-info">Please import csv</p>
            {% else %}
            {% for file_name in files %}
            <div class="myradio">
                <label for="file_name{{ forloop.counter }}"><input id="file_name{{ forloop.counter }}" name="file_name" type="radio" value="{{ file_name }}" required> {{ file_name }}</label>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    
        <div class="col">
            <h5>Select Algorithm</h5>
            {% if algorithms|length < 1 %}
                <p class="text-info">Contact the admin to upload algorithms</p>
            {% else %}
            {% for algorithm in algorithms %}
            <div class="myradio">
                <label for="{{ algorithm }}"><input id="{{ algorithm }}" name="algorithm" type="radio" value="{{ algorithm }}" required> {{ algorithm }}</label>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    
        </div>
        <button type="submit" class="btn btn-primary" id='run_analytic' name='analytic'> Run Analytic</button>
        </div>
    </form>
    <hr/>

MLWebApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">{% block nav %}{% endblock %}</span>
      </nav>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->

    {% block content %}
    {% endblock %}

  </body>
</html>

MLWebApp/templates/index.html
{% extends 'base.html' %}
{% block nav %}ML Analytics{% endblock %}
{% block title %}ML Analytics{% endblock %}

{% block content %}
<br/>
<div class="text-center"><h4>Welcome to Machine Learning Analytic</h4></div>
<hr/>
<!-- Upload file html -->
<div class="container">
    <div class="row">
        <!-- uploading new csv -->
        <div class="col border-right">
            <h5>Upload CSV</h5>
            <form  method="post" enctype="multipart/form-data" id="upload" >
                {% csrf_token %}
                <label for="id_upload_file_name">Dataset name: </label>
                <input type="text" name="file_name" required id="id_upload_file_name"/><br><br>
                <label for="id_document">File: </label>
                <input type="file" name="file_content" required id="id_document"><br><br>
                <button type="submit" class="btn btn-primary" name='upload'>Upload file</button>
                <b>{{ status }}</b>
            </form>
        </div>

        <!-- existing csv -->
        <div class="col border-right">
            <h5>Existing CSV</h5>
                <p class="text-muted">{{file.file_name}}
                {% for file_name in files %}
                    <form  method="POST" enctype="multipart/form-data" id="delete" action="{%url 'MLWebApp:delete' file_name %}" >
                    {% csrf_token %}
                    <!-- <p>{{ file.file_name }}</p> -->
                    <span> {{file_name}}</span>
                    {% if file_name %}
                    <button class = "center" ;type="submit" style="position: absolute; right: 0; background-color:red;color:white; font-size: 10px; border-radius: 5px;
                        left: 140px;
                        right: 380px"; name='delete'>delete</button>
        
                    <br>
                    {% endif %}
                    </form>
                {% endfor %}
                </p>
                <b>{{ status2 }}</b>
        </div>
    </div>
</div>
<hr/>

{% include 'analytic_template.html' %}

{% if result_plot %}
<div class="text-center">
    <center>
    <h5>result</h5>
    {{ result_plot | safe }}
    </center>
</div>
{% endif %}

{% endblock %}